#!/bin/bash

{
  echo SECRET_KEY=$SECRET_KEY
  FRONT_END_LOCATION=$FRONT_END_LOCATION
  DB_NAME=$DB_NAME
  DB_USER=$DB_USER
  DB_PASSWORD=$DB_PASSWORD
  DB_PORT=$DB_PORT
  EMAIL_PASSWORD='foo'
  ALLOWED_HOSTS='.localhost,127.0.0.1,[::1]'
} >> .env
