# Generated by Django 4.1.7 on 2023-03-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=240, verbose_name='full_name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone_number')),
                ('username', models.CharField(max_length=240, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=240, verbose_name='item_name')),
                ('item_des', models.TextField(max_length=240, verbose_name='item_des')),
                ('item_upload_date', models.DateField()),
                ('item_expiration_date', models.DateField()),
                ('item_provider', models.CharField(max_length=240, verbose_name='item_provider')),
                ('item_status', models.CharField(max_length=240, verbose_name='item_status')),
                ('item_isPrivate', models.BooleanField(default=False)),
                ('item_location', models.CharField(max_length=240, verbose_name='item_location')),
                ('item_isExpired', models.BooleanField(default=False)),
                ('item_pic', models.CharField(default='PATH', max_length=240, verbose_name='item_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_date', models.DateField(auto_now_add=True)),
                ('order_donation_amount', models.IntegerField(default=0)),
                ('order_isCollected', models.BooleanField(default=False)),
                ('order_isDeleted', models.BooleanField(default=False)),
                ('order_collected_date', models.DateField(auto_now_add=True)),
                ('order_collection_location', models.CharField(max_length=240, verbose_name='order_location')),
                ('order_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_initiator', to=settings.AUTH_USER_MODEL)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparefood.item')),
            ],
        ),
    ]
