# Generated by Django 4.1.7 on 2023-03-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_isprivate',
        ),
    ]
