# Generated by Django 4.1.7 on 2023-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0002_remove_items_item_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_isprivate',
            field=models.BooleanField(default=False),
        ),
    ]
