# Generated by Django 4.1.7 on 2023-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0003_items_item_isprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_isprivate',
            field=models.BooleanField(),
        ),
    ]
