# Generated by Django 4.1.7 on 2023-03-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0004_alter_items_item_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_pricing',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_isprivate',
            field=models.IntegerField(),
        ),
    ]
