# Generated by Django 4.1.7 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0005_remove_items_item_pricing_alter_items_item_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_isprivate',
        ),
        migrations.AddField(
            model_name='items',
            name='item_isExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_pic',
            field=models.CharField(default='PATH', max_length=240, verbose_name='item_pic'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
