# Generated by Django 4.1.7 on 2023-03-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0006_remove_items_item_isprivate_items_item_isexpired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_date', models.DateField()),
                ('order_donation_amount', models.IntegerField(default=0)),
                ('order_isCollected', models.BooleanField(default=False)),
                ('order_isDeleted', models.BooleanField(default=False)),
                ('order_collected_date', models.DateField()),
                ('order_collection_location', models.CharField(max_length=240, verbose_name='order_location')),
                ('order_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='order_initiator', to='sparefood.users')),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='order_item_id', to='sparefood.items')),
                ('order_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='order_provider', to='sparefood.users')),
            ],
        ),
    ]
