# Generated by Django 4.1.7 on 2023-03-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0006_remove_items_item_isprivate_items_item_isexpired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_account',
            field=models.CharField(max_length=240, unique=True, verbose_name='user_account'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.CharField(max_length=240, unique=True, verbose_name='user_email'),
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sparefood.users')),
            ],
        ),
    ]
