# Generated by Django 4.1.7 on 2023-03-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0007_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_provider',
        ),
    ]
