# Generated by Django 4.1.7 on 2023-03-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0008_remove_orders_order_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_item_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_item_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_username', to='sparefood.items'),
        ),
    ]
