# Generated by Django 4.1.7 on 2023-03-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0009_remove_orders_order_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_item_username',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_item_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='order_item_id', to='sparefood.items'),
        ),
    ]
