# Generated by Django 4.1.7 on 2023-03-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0010_remove_orders_order_item_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='order_item_id', to='sparefood.items'),
        ),
    ]
