# Generated by Django 4.1.7 on 2023-03-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparefood', '0011_alter_orders_order_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparefood.items'),
        ),
    ]
